### ISSUE TITLE
Provide a slim version without recovery module

### ISSUE THREAD

**Issue by ashchan** [cryptape/ruby-bitcoin-secp256k1#5]
And removed ruby interfaces for that module.

**Comment by ashchan** [comment]
@xxuejie Our install script enables these modules by default:

```shell
./configure --enable-module-recovery \
 --enable-experimental \
 --enable-module-ecdh \
 --enable-module-schnorr
```

Is `recovery` the only module we want to be able to disable?

**Comment by xxuejie** [comment]
My point is there will be people like me who will just install secp256k1 in standard packages, or have existing secp256k1 installations. By default, secp256k1 is compiled without `recovery module`, that's why I think we should also support the secp256k1 version where `recovery` module is disabled in this gem.

**Comment by ashchan** [comment]
@xxuejie  Makes sense to me. Perhaps a possible approach:

* Update the script to install secp256k1 with default configuration. 
* Add instructions on how to enable `recovery` should that be needed.
* Do some check when the gem is loaded and only attach `recovery` related C functions if it's able to call that module.

**Comment by xxuejie** [comment]
@ashchan I think we can only do this for now:

> Do some check when the gem is loaded and only attach recovery related C functions if it's able to call that module.

Later #6 would solve this issue completely.

**Comment by ashchan** [comment]
ok.
